//*-------  SYNTAX (BICIMLENDIRILMIS CUMLELER)  --------*/

//* PROGRAMIN LANGUAGES LIKE HUMAN LANGUAGES ENGLISH, TURKISH AND
//* MANY OTHER LANGUAGES USING THR WORDS, PHRASES SENTENCES, PROGRAMING
//* LANGUAGES IS ALSO HAVE SYNTAX.
//* JAVASCRIPT HAS IT IS OWN SYNTAX. IF WE DO NOT WRITE SYNTAX THAT JAVASCRIPT UNDERSTANDS.
//* IT WILL RAISE DIFFERENT YPE OF ERRORS

//*--------  SYNTAX ERRORS  --------*/

//* console.log("Hello Madam');
//! uncought sytanx error: invalid or unexpeted token
//! CHOSING THE QUOTES MSUT BE THE SAME IF IT IS
//! DOUBLE START FINISH WITH DOUBLE IF IT IS SINGLE FINISH WITH SINGLE QUOTE

//* console.log('Hello MR.O);
//! uncought sytanx error: invalid or unexpeted token
//! QUOTES SHOULD BE CLOSED!!!

//* console.log('Hello Kitty'
//! //! uncought sytanx error: Missing ) after argument list
//! Paranthesis should be also closed!!!

//* IF WE ARE PRIGINTING THE TEXT OR STRING USING THE CONSOLE.LOG
//*TEST OR STRING MUS BE WITHIN
//* - SINGLE QUOTES('')
//* - DOUBLE QUOTES ("")
//* - BACKTICK QUOTES (``)

//? ('HELLO MAMY')
//? ("HELLO DADY")
//? (`HELLO JHON`)
