//*--------    ARITHMETICS     ---------*/

//* IN ADDITIONS TO THE TEXT WE CAN ALSO ADD
//* MATEMATICAL CALCULATIONS USING JAVASCRIPT

//* (+) CUM ADDITION;

console.log(5 + 3);
//? 8

console.log(5 + 7 + 1);
//? 13

//* (-) SUBSTRACTION;

console.log(8 - 4);
//? 4

console.log(50 - 13);
//? 37

//* (*) MULTIPLICATION;

console.log(4 * 4);
//? 16

console.log(2 * 6);
//? 12

//* (/) DIVISION;

console.log(25 / 5);
//? 5

console.log(98 / 12);
//? 9

//* (%)MODULUS (MODE);

console.log(5 / 3);
//? 2

console.log(13 / 4);
//? 1

//* (**) EXPONENTATION;

console.log(2 ** 2);
//? 2x2=4

console.log(4 ** 3);
//? 64
