//*  ---------  CONDITIONALS  ----------  */

//* WE USED THE CONDITIONS STATEMENTS MAKE TO DECISIONS BASED ON THE DIFFERENT CONDITIONS
//* STATEMENTS IN JAVASCRIPT EXECUTED FROM TOP TO DOWN
//*IF THE PROCESSING LOGIC REQUIRES IT , THE SEQUENTIAL FLOW OF EXECUTION
//* CAN BE CHANGE IN TWO WAYS

//*   - CONSITIONAL EXECUTION

//*A BLOCK OF ONE OR MORE STATEMENTS WILL BE EXECUTED IF CERTAIN EXPRESSION IS TRUE

//*   - REPETITIVE EXECUTION

//* A BLOCK ONE OR MORE STATEMENTS WILL BE REPETITIVELY
//* EXECUTED AS LONG AS A CERTAIN EXPRESSION IS TRUE

//* - IF
//* - IF ELSE
//* - IF ELSE IF ELSE
//* - SWICTH
//* - TERNARY OPERATOR
