//*  ------------------- IF ------------------  */
/*
if (condition) {
}

let num = 3;
if (num > 0) {
  console.log(`${num} is a positive number`);
}
*/
//* AS  WE CAN SEE IN THE CONDITION EXAMPLE ABOVE 3 IS GREATHER THAN "0" SO IT IS A POSITIVE
//* NUMBER.THE CONDITION WAS TRUE AND THE BLOCK OF THE CODE WAS EXECUTED.
//* HOW EVER IF THE CONDITION IS "FALSE" WE WILL NOT SEE ANY RESULT IN CONSOLE
/*
let isRaining = true;
if (isRaining);
console.log(`You need a rain coat`);
*/
//* THE SAME GOES FOR THE SCOND CONDITION, IF "isRaining" IS FALSE
//* THE IF BLOCK WILL NOT BE EXECUTEDAND WE DO NOT SEE ANY OUTPUT
//* IN ORDER TO SEE THE RESULT OF FALSY CONDITIONS. WE SHOULD HAVE
//* ANOTHER BLOCK WHICH IS GOING TO BE "ELSE"

//*  ------------------- IF ELSE ------------------  */

//* IF THE CONDITION IS TRUE THE FIRST BLOCK WILLBE EXECUTED, IF NOT
//* THE ELSE CONDITONS WILL BE EXECUTED
/*

if (condition) {
} else {
}

*/
/*
let num1 = -3;
if (num1 > 0) {
  console.log(`${num1} is a positive number`);
} else {
  console.log(`${num1} is a negative number`);
}
*/
/*
let num3 = 3;
if (num3 > 0) {
  console.log(`${num3} is a positive number`);
} else {
  console.log(`${num3} is a negative number`);
}
*/
/*
let isSnowing = true;
if (isSnowing) {
  console.log("You need parke");
} else {
  console.log("Wheather not snowy");
}
*/
//*  ------------------- IF ELSE IF ELSE------------------  */

//* EVERYDAY WE MAKE DECISIONS, NOT ONLY ONE OR TWO DECISIONS WE DO SOMETIMES

/*
if (condition){
console.log()
}else if{
console.log
}else {
console.log()
}
*/
/*
let a = 0;

if (a > 0) {
  console.log(`${a} is a postive number`);
} else if (a == 0) {
  console.log(`${a} is a negative number`);
} else {
  console.log(`${a} is not a number!!`);
}
  
/*
let weather = "sunny";
if (weather === "rainy") {
  console.log(`You need a rain coat`);
} else if (weather === "sunny") {
  console.log(`Maybe you will need a rain coat`);
} else {
  console.log(`No need to weat coat`);
}

*/
