//*  -----------------  WINDOW METHOD  ---------------  */

//* - WINDOW ALERT()METHOD

//* AS WE SAW IIN THE BEGGINING "alert()"
//* METHOD DISPLAYS AND ALER BOS WITH SPECIFIED MESSAGE

//* aler(message)

alert("Please be carefull !!!");

//* - WINDOW PROMPT() METHOD

//* DISPLAYS THE A PROMPT BOX WITH AN IMPUT ON YOUT BROWSER TO TAKE INPUT
//* VALUES AND THE INPUT DATA CAN BE STORED IN A VARIABLE
//* THE PROMPT() METHODS TAKES TWO ARGUEMNTS THE SOCND ARGIEMNT IS OPTIONAL

prompt("required text", "optional text");

//* - WINDOW CONFIRM() METHOD

//* THE CONFIRM() METHOD DISPLAYS A DIALOG BOX WITH A SPECIFIC MESSAGE, ALONG WITH AN "OK"
//* AND A "CANCEL" BUTTON
//* A CONFIRM BOX IS OFFEN USED TO ASK THE PERMISSION
//* FROM A USED TO EXECUTE SOMETHING

const agrement = confirm("Would you like to cancel your data?"); //? TAKE A STRING AS AN ARGUMANT

//! IF WE CLICK "OK" OUTCOME TRUE
//!IF WE CLICK "NO" OUTCOME FALSE
